### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by thomas502** [lz0423/ceshi#2]
Run node index.js unicom --user=${user} --*** --appid=${appid}
总账户数 1
将使用 13******170 作为账户识别码
获得配置文件 /home/runner/.AutoSignMachine/taskFile_unicom_13******170.json 当前日期 20210312
日期已变更，重新生成任务配置
计算可执行任务 总任务数 48 已完成任务数 0 错误任务数 0 指定任务数 0 预计可执行任务数 2
开始执行任务
dailyCourse: 获得登录状态成功
exchangeDFlowCircle: 调度任务中 并发数 2
dailyCourse: 延迟执行 dailyCourse 221 seconds
exchangeDFlowCircle: 剩余流量 2092.49 MB 检查限制 200 MB
exchangeDFlowCircle: 跳过兑换流量包
exchangeDFlowCircle: exchangeDFlowCircle 执行用时 1 秒
本次已结束，下次继续努力哦
dailyCourse 执行用时 223 秒
今日获得奖品信息统计
当前任务执行完毕！

日志就是这个 请问是哪里出问题了吗

**Comment by thomas502** [comment]
![网页捕获_12-3-2021_155815_github com](https://user-images.githubusercontent.com/80235156/110910074-d5578280-834b-11eb-9c63-0a81bd0c7124.jpeg)

**Comment by thomas502** [comment]
![网页捕获_12-3-2021_155815_github com](https://user-images.githubusercontent.com/80235156/110911165-4cd9e180-834d-11eb-9d68-ba024cd7fcd3.jpeg)

**Comment by lz0423** [comment]
时间问题，晚上11点之后，才有所有的任务，或者自己克隆手机上运行，改手机时间

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月12日(周五) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lz0423/ceshi] 运行不了 (#2)
